<template>
  <div class="flex items-center mt-10 mx-auto h-auto">
    <svg
      xmlns="http://www.w3.org/2000/svg"
      class="w-20 h-20 mx-auto"
      xmlns:xlink="http://www.w3.org/1999/xlink"
      style="
        margin: auto;
        background: #fff;
        display: block;
        shape-rendering: auto;
      "
      width="100px"
      height="100px"
      viewBox="0 0 100 100"
      preserveAspectRatio="xMidYMid"
    >
      <g transform="translate(50 50)">
        <g transform="scale(0.7)">
          <g transform="translate(-50 -50)">
            <g>
              <animateTransform
                attributeName="transform"
                type="rotate"
                repeatCount="indefinite"
                values="0 50 50;360 50 50"
                keyTimes="0;1"
                dur="1.5s"
              ></animateTransform>
              <path
                fill-opacity="0.8"
                fill="url(#grad1)"
                d="M50 50L50 0A50 50 0 0 1 100 50Z"
              ></path>
            </g>
            <g>
              <animateTransform
                attributeName="transform"
                type="rotate"
                repeatCount="indefinite"
                values="0 50 50;360 50 50"
                keyTimes="0;1"
                dur="2s"
              ></animateTransform>
              <path
                fill-opacity="0.8"
                fill="url(#grad2)"
                d="M50 50L50 0A50 50 0 0 1 100 50Z"
                transform="rotate(90 50 50)"
              ></path>
            </g>
            <g>
              <animateTransform
                attributeName="transform"
                type="rotate"
                repeatCount="indefinite"
                values="0 50 50;360 50 50"
                keyTimes="0;1"
                dur="3s"
              ></animateTransform>
              <path
                fill-opacity="0.8"
                fill="url(#grad3)"
                d="M50 50L50 0A50 50 0 0 1 100 50Z"
                transform="rotate(180 50 50)"
              ></path>
            </g>
            <g>
              <animateTransform
                attributeName="transform"
                type="rotate"
                repeatCount="indefinite"
                values="0 50 50;360 50 50"
                keyTimes="0;1"
                dur="4.5s"
              ></animateTransform>
              <path
                fill-opacity="0.8"
                fill="url(#grad4)"
                d="M50 50L50 0A50 50 0 0 1 100 50Z"
                transform="rotate(270 50 50)"
              ></path>
            </g>
          </g>
        </g>
      </g>
      <!-- Gradient Definitions -->
      <defs>
        <linearGradient id="grad1" x1="0%" y1="0%" x2="100%" y2="0%">
          <stop offset="0%" style="stop-color: #7095bb; stop-opacity: 1" />
          <stop offset="100%" style="stop-color: #486581; stop-opacity: 1" />
        </linearGradient>
        <linearGradient id="grad2" x1="0%" y1="0%" x2="100%" y2="0%">
          <stop offset="0%" style="stop-color: #559bc9; stop-opacity: 1" />
          <stop offset="100%" style="stop-color: #3a7aae; stop-opacity: 1" />
        </linearGradient>
        <linearGradient id="grad3" x1="0%" y1="0%" x2="100%" y2="0%">
          <stop offset="0%" style="stop-color: #2d6ea7; stop-opacity: 1" />
          <stop offset="100%" style="stop-color: #1b537f; stop-opacity: 1" />
        </linearGradient>
        <linearGradient id="grad4" x1="0%" y1="0%" x2="100%" y2="0%">
          <stop offset="0%" style="stop-color: #114a70; stop-opacity: 1" />
          <stop offset="100%" style="stop-color: #0b3350; stop-opacity: 1" />
        </linearGradient>
      </defs>
      <!-- [ldio] generated by https://loading.io/ -->
    </svg>
  </div>
</template>

<style scoped>
.loader {
  position: absolute;
  top: 50%;
  left: 50%;
  height: 60px;
  width: 100px;
  margin: 0;
  -webkit-transform: translate(-50%, -50%);
  transform: translate(-50%, -50%);
}
</style>
